@Observed
export class CommonConstants {
  static readonly FONT_SIZE_12: number = 12;

  static readonly FONT_SIZE_16: number = 16;

  static readonly FONT_SIZE_18: number = 18;

  static readonly FONT_SIZE_20: number = 20;

  static readonly FONT_SIZE_24: number = 24;

  static readonly FONT_SIZE_32: number = 32;

  static readonly FONT_SIZE_36: number = 36;

  static readonly COLOR_WHITE: ResourceColor = '#FFFFFF';

  static readonly TEXT_COLOR_182431: ResourceColor = '#182431';

  static readonly TEXT_COLOR_99182431: ResourceColor = '#99182431';

  static readonly TEXT_COLOR_FF660000: ResourceColor = '#660000';

  static readonly EDIT_BOX_DEFAULT_HINT_COLOR: ResourceColor = '#99182431';

  static readonly BINDER_BOX_HEIGHT_VP: number = 56;

  static readonly INPUT_TEXT_BASELINE_OFFSET: number = 8;

  static readonly SEARCH_BUTTON_SIZE_VP: number = 36;

  static readonly CONTENT_PADDING: number = 24;

  static readonly BUTTON_WIDTH_VP: number = 360;

  static readonly IMAGE_MODULAR_WIDTH_VP: number = 360;

  static readonly CARD_BORDER_RADIUS: number = 8;

  static readonly BANNER_HEIGHT_VP: number = 191;

  static readonly BAR_HEIGHT_VP: number = 40;

  static readonly PADDING_LEFT: number = 12;

  static readonly RICH_TEXT_HEIGHT: number = 48;

  static readonly CONTENT_MODULAR_SPACING: number = 24;

  static readonly TEXT_MODULAR_SPACING: number = 8;

  static readonly TITLE_MODULAR_SPACING: number = 12;

  static readonly IMAGE_MODULAR_SPACING: number = 16;

  static readonly POPUP_PADDING: number = 16;

  static readonly POPUP_BORDER_RADIUS: number = 8;
}